<?php
/**
 * @file
 * stembook_site.features.field.inc
 */

/**
 * Implements hook_field_default_fields().
 */
function stembook_site_field_default_fields() {
  $fields = array();

  // Exported field: 'node-nodeblock-body'.
  $fields['node-nodeblock-body'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(
        0 => 'node',
      ),
      'field_name' => 'body',
      'field_permissions' => array(
        'type' => '0',
      ),
      'foreign keys' => array(
        'format' => array(
          'columns' => array(
            'format' => 'format',
          ),
          'table' => 'filter_format',
        ),
      ),
      'indexes' => array(
        'format' => array(
          0 => 'format',
        ),
      ),
      'locked' => '0',
      'module' => 'text',
      'settings' => array(
        'profile2_private' => FALSE,
      ),
      'translatable' => '1',
      'type' => 'text_with_summary',
    ),
    'field_instance' => array(
      'bundle' => 'nodeblock',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'hidden',
          'module' => 'text',
          'settings' => array(),
          'type' => 'text_default',
          'weight' => 0,
        ),
        'teaser' => array(
          'label' => 'hidden',
          'module' => 'text',
          'settings' => array(
            'trim_length' => 600,
          ),
          'type' => 'text_summary_or_trimmed',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'body',
      'label' => 'Body',
      'required' => FALSE,
      'settings' => array(
        'display_summary' => TRUE,
        'text_processing' => 1,
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'module' => 'text',
        'settings' => array(
          'rows' => 20,
          'summary_rows' => 5,
        ),
        'type' => 'text_textarea_with_summary',
        'weight' => '-4',
      ),
    ),
  );

  // Exported field: 'node-nodeblock-scf_f_machine_name'.
  $fields['node-nodeblock-scf_f_machine_name'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'scf_f_machine_name',
      'foreign keys' => array(),
      'indexes' => array(
        'machine' => array(
          0 => 'machine',
        ),
      ),
      'locked' => '0',
      'module' => 'safeword',
      'settings' => array(
        'allow_machine_changes' => 1,
        'machine_description' => 'The machine may only contain lowercase letters, numbers and underscores.',
        'machine_label' => 'Machine name',
        'max_length' => '32',
        'replace_pattern' => '[^a-z0-9_]+',
        'replace_value' => '_',
        'unique' => 1,
      ),
      'translatable' => '0',
      'type' => 'safeword',
    ),
    'field_instance' => array(
      'bundle' => 'nodeblock',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => '1',
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'scf_f_machine_name',
      'label' => 'Machine name',
      'required' => 0,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 0,
        'module' => 'safeword',
        'settings' => array(),
        'type' => 'safeword_machine_name',
        'weight' => '-3',
      ),
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Body');
  t('Machine name');

  return $fields;
}
