<?php
/**
 * @file
 * Code for the f_stembook feature.
 */

include_once('f_stembook.features.inc');

/**
 * Implements hook_node_view().
 */
function f_stembook_node_view($node, $view_mode, $langcode) {
  // Set menu tree path so that the menu block appears on node full views.
  if ($node->type == 'pubnode' || $node->type == 'stembook_chapter_new') {
    menu_tree_set_path('main-menu', 'chapters');
  }
}

/**
 * Implements hook_filter_info().
 */
function f_stembook_filter_info() {
  $filters['_stembook_filter_html_entrezgene'] = array(
    'title' => t('Add EntrezGene links'),
    'process callback' => '_stembook_filter_html_entrezgene',
    //'cache' => FALSE,
  );
  $filters['_stembook_filter_html_a_name'] = array(
    'title' => t('Remove name attribute in a tags'),
    'process callback' => '_stembook_filter_html_a_name',
    //'cache' => FALSE,
  );
  $filters['_stembook_filter_html_dev_links'] = array(
    'title' => t('Change links pointing to dev.www.stembook.org to www.stembook.org'),
    'process callback' => '_stembook_filter_html_dev_links',
    //'cache' => FALSE,
  );
  return $filters;
}

/**
 * HTML filter to add links to entrezgenes.
 */
function _stembook_filter_html_entrezgene($text, $filter) {
  $html_dom = filter_dom_load($text);
  $links = $html_dom->getElementsByTagName('span');
  foreach ($links as $node) {

    // Extract entrezgene id.
    $entrez_id = '';
    if ($node->getAttribute('noderef')) {
      $elements = explode('=', $node->getAttribute('noderef'));
      if ($elements[0] == 'entrezgene') {
        $entrez_id = $elements[1];
      }
      // Remove noderef attribute since it does not validate.
      $node->removeAttribute('noderef');
    }

    if ($entrez_id) {
      $text = $node->textContent;
      $node->removeChild($node->firstChild);
      $link = $html_dom->createElement('a', $text);
      $link->setAttribute('href', 'http://purl.org/commons/record/ncbi_gene/' . $entrez_id);
      $node->appendChild($link);
    }
  }
  $text = filter_dom_serialize($html_dom);

  return trim($text);
}

/**
 * HTML filter to remove name attributes in links.
 */
function _stembook_filter_html_a_name($text, $filter) {
  $html_dom = filter_dom_load($text);
  $ps = $html_dom->getElementsByTagName('p');
  foreach ($ps as $p) {
    if ( !empty($p->childNodes->item(0)->tagName) &&
         $p->childNodes->item(0)->tagName == 'a' &&
         !empty($p->childNodes->item(1)->tagName) &&
         $p->childNodes->item(1)->tagName == 'br' &&
         empty($p->childNodes->item(2)->tagName) ) {
      $p->removeChild($p->childNodes->item(1));
    }
  }

  $links = $html_dom->getElementsByTagName('a');
  foreach ($links as $node) {
    if ($node->getAttribute('name')) {
      // Remove name attribute since it does not validate.
      $node->removeAttribute('name');
    }
  }

  $text = filter_dom_serialize($html_dom);

  return trim($text);
}

/**
 * Change links pointing to dev.www.stembook.org to www.stembook.org.
 */
function _stembook_filter_html_dev_links($text, $filter) {
  return preg_replace('/dev.www.stembook.org/', 'www.stembook.org', $text);
}
