<?php
/**
 * @file
 * Code for the scf_site feature.
 */

include_once 'scf_site.features.inc';

/**
 * Implements hook_block_info().
 */
function scf_site_block_info() {
  $block = array();

  // Customize this block as needed for your site. This block is generated
  // programmatically as some links are dependent on whether the user is
  // logged in or not.
  $blocks['user_top_menu'] = array(
    // Admin block title (admin area only).
    'info' => t('scf_site: User top menu'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function scf_site_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'user_top_menu':
      // Rendered block title. Leave it empty if you don't want to display it.
      $block['subject'] = t('');
      $block['content'] = scf_site_user_top_menu_block_content();
      break;
  }
  return $block;
}

/**
 * Renders content for the scf_site_user_top_menu block
 */
function scf_site_user_top_menu_block_content() {
  global $user;
  $account = user_load($user->uid);

  $output = '';

  // First row of links (about us ...).
  $links = array();
  $links[] = l(t('About Us'), 'about');
  $links[] = l(t('Image Credits'), 'credits');
  $links[] = l(t('Contributor Info'), 'contributor-info');
  $links[] = l(t('RSS'), 'rss.xml');
  $output .= theme('item_list', array('items' => $links, 'attributes' => array('id' => 'scf_site_user_menu1', 'class' => 'menu')));

  // Second row of links (log in ...).
  $links = array();
  if(user_is_logged_in()) {
    $links[] = l(t('Welcome !username', array('!username' => format_username($account))), 'user');
    $links[] = l(t('Log Out'), 'user/logout');
  }
  else {
    $links[] = l(t('Log In'), 'user/login');
    $links[] = l(t('Join'), 'user/register');
  }
  $links[] = l(t('E-Alerts'), 'ealerts');
  $output .= theme('item_list', array('items' => $links, 'attributes' => array('id' => 'scf_site_user_menu2', 'class' => 'menu')));

  // Third row of links (download e-book).
  $links = array();
  $links[] = l(t('Download E-Book'), 'sites/default/files/ebook/scf-ebook.epub');
  $output .= theme('item_list', array('items' => $links, 'attributes' => array('id' => 'scf_site_user_menu3', 'class' => 'menu')));

  return $output;
}
