<?php

/**
 * Implements hook_block_info().
 */
function pubnode7_block_info() {
  $blocks['toc']['info'] = t('Table of Contents');
  $blocks['pubnode']['cache'] = DRUPAL_CACHE_PER_PAGE;

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function pubnode7_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'toc':
      $block['subject'] = t('Table of Contents');
      // The ToC is stored in the pubnode table.
      $toc = db_query("SELECT toc FROM {pubnode} WHERE nid = :nid", array(':nid' => arg(1)))->fetchField();
      if ($toc) {
        $block['content'] = $toc;
      }
      break;
  }
  return $block;
}

