<?php
/**
 * @file
 * Code for the scf_protocols feature.
 */

include_once 'scf_protocols.features.inc';

/**
 * Implements hook_node_view().
 */
function scf_protocols_node_view($node, $view_mode, $langcode) {
  // Set menu tree path so that the menu block appears on node full views.
  if ($node->type == 'protocol' || $node->type == 'scf_protocol') {
    menu_tree_set_path('main-menu', 'protocols');
  }
}
